Repository selsa-inube/inubekit-header, pull requests merged in 2024-10, with the labels that each got.

#55 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#56 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#57 Extend `<Header />` to integrate `<User />` with custom menu
  package.json
  src/Header/index.tsx
  src/Header/stories/Header.stories.tsx
  src/Header/styles.js
Labels: enhancement, minor

#58 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#59 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#60 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#61 feat: extend navigation, user, and links props and update user dep
  .storybook/preview.ts
  package.json
  src/Header/index.tsx
  src/Header/stories/Header.stories.tsx
  src/Header/styles.js
Labels: major
